apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ak-project-cd # v spoločnom klastri je nasadených viacero takýchto objektov
  namespace: wac-hospital
spec:
  wait: true
  interval: 42s
  path: clusters/wac-aks
  prune: true
  sourceRef:
    kind: GitRepository
    name: ak-project-gitops-repo