apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ak-project-gitops-repo # v spoločnom klastri je nasadených viacero takýchto objektov
  namespace: wac-project
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/akoricansky/project-counseling

# ak používate privátny repozitár nezabudnite doplniť autentifikačné údaje
# secretRef:
#    name: <pfx>-repository-pat