apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app.kubernetes.io/part-of: wac-project
    app.kubernetes.io/name: ak-counseling

namespace: wac-project

resources:
- cd.kustomization.yaml
- install.kustomization.yaml
- git-repository.yaml