apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: ak-ambulance-counseling-fe
  includeSelectors: true
  includeTemplates: true

resources:
- ../../../apps/ak-ambulance-counseling-fe


components:
- ../../../components/version-release