apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-project

labels:
- pairs:
    app.kubernetes.io/part-of: wac-project
    app.kubernetes.io/name: ak-counseling
  includeSelectors: true
  includeTemplates: true

resources:
- ../../../apps/ak-counseling


components:
- ../../../components/version-release